kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: amq-consumer
  labels:
    app: amq-consumer
    app.kubernetes.io/component: amq-consumer
    app.kubernetes.io/instance: amq-consumer
    app.kubernetes.io/name: amq-consumer
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-17-ubi8
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'amq-consumer:latest'
  resources: {}
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 1
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'java:openjdk-17-ubi8'
  source:
    type: Git
    git:
      uri: 'https://github.com/ippul/amq-auth-keycloak.git'
    contextDir: /amq-consumer
    configMaps:
      - configMap:
          name: maven-settings
        destinationDir: .
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: amq-consumer-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: amq-consumer-github-webhook-secret
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  runPolicy: Serial
