apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: amq-init
spec:
  output:
    to:
      kind: ImageStreamTag
      name: amq-init:latest
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 1
  source:
    dockerfile: |-
      FROM registry.redhat.io/amq7/amq-broker-init-rhel8:7.10-38.1675807822
      USER root
      RUN mkdir -p /amq/scripts/
      RUN cp /opt/custom/post-config.sh /amq/scripts/post-config.sh
      RUN chmod -R 777 /amq/scripts
  runPolicy: Serial
  triggers:
  - imageChange:
      from:
        kind: ImageStreamTag
        name: amq-broker-init-rhel8:7.10-38.1675807822
        namespace: {{ .Release.Namespace }}
    type: ImageChange
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'amq-broker-init-rhel8:7.10-38.1675807822'
      volumes:
        - name: post-config
          source:
            type: ConfigMap
            configMap:
              name: post-config
              defaultMode: 420
          mounts:
            - destinationPath: /opt/custom/
