kind: Deployment
apiVersion: apps/v1
metadata:
  name: amq-consumer
  labels:
    app: amq-consumer
    app.kubernetes.io/component: amq-consumer
    app.kubernetes.io/instance: amq-consumer
    app.kubernetes.io/name: amq-consumer
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-17-ubi8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amq-consumer
  template:
    metadata:
      labels:
        app: amq-consumer
        deployment: amq-consumer
    spec:
      containers:
        - name: amq-consumer
          image: 'image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/amq-consumer:latest'
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600