---
apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: amq-broker-sso
  labels:
    app: rhsso
spec:
  instances: 1
  externalAccess:
    enabled: true
  keycloakDeploymentSpec:
    resources:
      requests:
        cpu: "500m"
      limits:
        cpu: "1"
