---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: amq-broker
  labels:
    app: rhsso
spec:
  realmSelector:
     matchLabels:
      app: rhsso
  roles:
    - name: admin
    - name: consumer
    - name: producer
  client:
    clientId: amq-broker
    name: amq-broker
    description: amq-broker
    protocol: openid-connect
    clientAuthenticatorType: client-secret
    secret: amq-broker-secret-value
    standardFlowEnabled: false
    directAccessGrantsEnabled: true
    serviceAccountsEnabled: false
    defaultClientScopes:
      - email
      - profile
      - roles
      - web-origins
    optionalClientScopes:
      - address
      - microprofile-jwt
      - offline_access
      - phone
